### NumPy experiment

In [1]:
import numpy as np


In [2]:
num_classes = 5
num_train = 10
num_dimension = 12  # Features

X = np.arange(120).reshape((num_train, num_dimension))
X.shape = (num_train, num_dimension)
X

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119]])

In [3]:
W = np.arange(60).reshape((num_dimension, num_classes)) # Features (row) X Classes (col)
W.shape = (num_dimension, num_classes) 
W = W * 0.1
W

array([[0. , 0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8, 0.9],
       [1. , 1.1, 1.2, 1.3, 1.4],
       [1.5, 1.6, 1.7, 1.8, 1.9],
       [2. , 2.1, 2.2, 2.3, 2.4],
       [2.5, 2.6, 2.7, 2.8, 2.9],
       [3. , 3.1, 3.2, 3.3, 3.4],
       [3.5, 3.6, 3.7, 3.8, 3.9],
       [4. , 4.1, 4.2, 4.3, 4.4],
       [4.5, 4.6, 4.7, 4.8, 4.9],
       [5. , 5.1, 5.2, 5.3, 5.4],
       [5.5, 5.6, 5.7, 5.8, 5.9]])

In [4]:
y = np.arange(num_classes)
#y.shape = (num_train,)
y

array([0, 1, 2, 3, 4])

In [5]:
# y[-5:] = y[0:5]
# y # correct class (index)

In [6]:
i = 0
j = 1
scores = X[i].dot(W)
scores  # Scores for each class

array([253. , 259.6, 266.2, 272.8, 279.4])

In [7]:
correct_class_score = scores[y[i]] 
correct_class_score

253.0

In [8]:
margin = scores[j] - correct_class_score + 1 # note delta = 1
margin

7.600000000000023

In [9]:
dW = np.zeros(W.shape) # initialize the gradient as zero
dW

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
dW[:, j]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
X[i]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
dW[:, j] += X[i]
dW[:, j]

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [13]:
dW

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.],
       [ 0.,  3.,  0.,  0.,  0.],
       [ 0.,  4.,  0.,  0.,  0.],
       [ 0.,  5.,  0.,  0.,  0.],
       [ 0.,  6.,  0.,  0.,  0.],
       [ 0.,  7.,  0.,  0.,  0.],
       [ 0.,  8.,  0.,  0.,  0.],
       [ 0.,  9.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.],
       [ 0., 11.,  0.,  0.,  0.]])

In [14]:
X[i]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
dW[:, y[i]] 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
dW[:, y[i]] -= X[i]

In [17]:
dW

array([[  0.,   0.,   0.,   0.,   0.],
       [ -1.,   1.,   0.,   0.,   0.],
       [ -2.,   2.,   0.,   0.,   0.],
       [ -3.,   3.,   0.,   0.,   0.],
       [ -4.,   4.,   0.,   0.,   0.],
       [ -5.,   5.,   0.,   0.,   0.],
       [ -6.,   6.,   0.,   0.,   0.],
       [ -7.,   7.,   0.,   0.,   0.],
       [ -8.,   8.,   0.,   0.,   0.],
       [ -9.,   9.,   0.,   0.,   0.],
       [-10.,  10.,   0.,   0.,   0.],
       [-11.,  11.,   0.,   0.,   0.]])

In [18]:
dW = np.zeros(W.shape) # initialize the gradient as zero
loss = 0.0
for i in range(num_train):
    scores = X[i].dot(W)
    # print(i, scores)
    correct_class_score = scores[y[i]]  # y[i] is the correct class (index)
    # print(correct_class_score)
    # margin_loss_count = 0
    for j in range(num_classes):
      if j == y[i]:
        continue
      print(i, j)
      margin = scores[j] - correct_class_score + 1 # note delta = 1
      print('score[',j,']', scores[j],'correct class score', correct_class_score, 'margin', margin)
      if margin > 0:
        loss += margin
        # margin_loss_count += 1
        # Computing the gradient analytically with Calculus
        # For incorrect classes
        dW[:, j] += X[i] # add X value to classes that are incorrect
        dW[:, y[i]] -= X[i] # subtract X value from the correct class
      print("dW:", dW)
    # For correct classes
    # dW[:, y[i]] += -1 * margin_loss_count * X[i]

    
# Right now the loss is a sum over all training examples, but we want it
# to be an average instead so we divide by num_train.
loss /= num_train
dW /= num_train

print('loss', loss)
print('dW', dW)

# Add regularization to the loss.
# loss += reg * np.sum(W * W)
# that contribues to the gradient as well

reg = 1

# dW += 2 * reg * W
dW += reg * W  # regularize the weights
# Add regularization to the loss.
loss += 0.5 * reg * np.sum(W * W)

print('loss', loss)
print('dW', dW)


0 1
score[ 1 ] 259.6 correct class score 253.0 margin 7.600000000000023
dW: [[  0.   0.   0.   0.   0.]
 [ -1.   1.   0.   0.   0.]
 [ -2.   2.   0.   0.   0.]
 [ -3.   3.   0.   0.   0.]
 [ -4.   4.   0.   0.   0.]
 [ -5.   5.   0.   0.   0.]
 [ -6.   6.   0.   0.   0.]
 [ -7.   7.   0.   0.   0.]
 [ -8.   8.   0.   0.   0.]
 [ -9.   9.   0.   0.   0.]
 [-10.  10.   0.   0.   0.]
 [-11.  11.   0.   0.   0.]]
0 2
score[ 2 ] 266.20000000000005 correct class score 253.0 margin 14.200000000000045
dW: [[  0.   0.   0.   0.   0.]
 [ -2.   1.   1.   0.   0.]
 [ -4.   2.   2.   0.   0.]
 [ -6.   3.   3.   0.   0.]
 [ -8.   4.   4.   0.   0.]
 [-10.   5.   5.   0.   0.]
 [-12.   6.   6.   0.   0.]
 [-14.   7.   7.   0.   0.]
 [-16.   8.   8.   0.   0.]
 [-18.   9.   9.   0.   0.]
 [-20.  10.  10.   0.   0.]
 [-22.  11.  11.   0.   0.]]
0 3
score[ 3 ] 272.80000000000007 correct class score 253.0 margin 20.800000000000068
dW: [[  0.   0.   0.   0.   0.]
 [ -3.   1.   1.   1.   0.]
 [ -6.   2.   

IndexError: index 5 is out of bounds for axis 0 with size 5

In [19]:
loss = 0.0
dW = np.zeros(W.shape) # initialize the gradient as zero
num_train = X.shape[0]
scores = X.dot(W)
yi_scores = scores[np.arange(scores.shape[0]), y]
margins = np.maximum(0, scores - np.matrix(yi_scores).T + 1)
margins[np.arange(num_train), y] = 0
loss = np.mean(np.sum(margins, axis=1))
loss += reg * np.sum(W * W)


binary = margins
binary[margins > 0] = 1
row_sum = np.sum(binary, axis=1)
binary[np.arange(num_train), y] = -row_sum.T
dW = np.dot(X.T, binary)

dW /= num_train

dW += reg * W


IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (10,) (5,) 

In [20]:
loss = 0.0
dW = np.zeros(W.shape) # initialize the gradient as zero
num_train = X.shape[0]
scores = X.dot(W)
scores

array([[ 253. ,  259.6,  266.2,  272.8,  279.4],
       [ 649. ,  670. ,  691. ,  712. ,  733. ],
       [1045. , 1080.4, 1115.8, 1151.2, 1186.6],
       [1441. , 1490.8, 1540.6, 1590.4, 1640.2],
       [1837. , 1901.2, 1965.4, 2029.6, 2093.8],
       [2233. , 2311.6, 2390.2, 2468.8, 2547.4],
       [2629. , 2722. , 2815. , 2908. , 3001. ],
       [3025. , 3132.4, 3239.8, 3347.2, 3454.6],
       [3421. , 3542.8, 3664.6, 3786.4, 3908.2],
       [3817. , 3953.2, 4089.4, 4225.6, 4361.8]])

In [21]:
np.arange(scores.shape[0])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
y

array([0, 1, 2, 3, 4])

In [24]:
row_mask = np.arange(scores.shape[0])
yi_scores = scores[list(range(num_train)), y]
# yi_scores = scores[ np.broadcast(np.arange(num_train)), np.broadcast(y) ] # 
    # scores[(0,1,2,3,4,5,6,7,8,9), (0,1,2,3,4)]
yi_scores

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (10,) (5,) 

In [34]:
# X_train = np.arange(30).reshape((10, 3))
# X_train

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [35]:
# X = np.random.randint(0, 30, (3, 3))
# X

array([[15, 13, 17],
       [16, 22, 29],
       [ 2, 25,  5]])

In [36]:
# dists = np.zeros((X.shape[0], X_train.shape[0]))
# dists

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
A = np.arange(12).reshape((3,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
SQ = A * A
SQ

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [27]:
SQ2 = A ** 2
SQ2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [28]:
SQ_SUM = np.sum(A * A)
SQ_SUM

506

In [11]:
num_test = X.shape[0]
num_train = X_train.shape[0]
dists = np.zeros((num_test, num_train))
for i in range(num_test):
    for j in range(num_train):
        dists[i][j] = np.sqrt(np.sum((X[i] - X_train[j])**2))
        
dists

array([[31.591138  , 26.92582404, 22.49444376, 18.46618531, 15.16575089,
        13.15294644, 13.03840481, 14.86606875, 18.05547009, 22.02271555],
       [24.71841419, 20.09975124, 15.84297952, 12.32882801, 10.34408043,
        10.77032961, 13.37908816, 17.20465053, 21.61018278, 26.30589288],
       [31.06444913, 27.09243437, 23.60084744, 20.83266666, 19.10497317,
        18.70828693, 19.72308292, 21.9544984 , 25.07987241, 28.80972058]])

In [12]:
num_test = X.shape[0]
num_train = X_train.shape[0]
dists = np.zeros((num_test, num_train))
for i in range(num_test):
    dists[i] = np.sqrt(np.sum((X[i] - X_train)**2, axis=1))
    
dists

array([[31.591138  , 26.92582404, 22.49444376, 18.46618531, 15.16575089,
        13.15294644, 13.03840481, 14.86606875, 18.05547009, 22.02271555],
       [24.71841419, 20.09975124, 15.84297952, 12.32882801, 10.34408043,
        10.77032961, 13.37908816, 17.20465053, 21.61018278, 26.30589288],
       [31.06444913, 27.09243437, 23.60084744, 20.83266666, 19.10497317,
        18.70828693, 19.72308292, 21.9544984 , 25.07987241, 28.80972058]])

In [13]:
# (a - b)**2 = a**2 + b**2 - 2*a*b
X_squared_sum = np.sum(X**2, axis=1)
X_squared_sum

array([1075,  666, 1074])

In [14]:
X_train_squared_sum = np.sum(X_train**2, axis=1)
X_train_squared_sum

array([   5,   50,  149,  302,  509,  770, 1085, 1454, 1877, 2354])

In [15]:
# 2 * X * X_train
two_x_x_tr = 2 * X.dot(X_train.T)
two_x_x_tr

array([[  82,  400,  718, 1036, 1354, 1672, 1990, 2308, 2626, 2944],
       [  60,  312,  564,  816, 1068, 1320, 1572, 1824, 2076, 2328],
       [ 114,  390,  666,  942, 1218, 1494, 1770, 2046, 2322, 2598]])

In [16]:
X_squared_sum.shape

(3,)

In [17]:
X_train_squared_sum.shape

(10,)

In [18]:
X_train_squared_sum

array([   5,   50,  149,  302,  509,  770, 1085, 1454, 1877, 2354])

In [19]:
X_sq_X_tr_sq = X_squared_sum[:, np.newaxis] + X_train_squared_sum
X_sq_X_tr_sq

array([[1080, 1125, 1224, 1377, 1584, 1845, 2160, 2529, 2952, 3429],
       [ 671,  716,  815,  968, 1175, 1436, 1751, 2120, 2543, 3020],
       [1079, 1124, 1223, 1376, 1583, 1844, 2159, 2528, 2951, 3428]])

In [20]:
X_X_tr_sq = X_sq_X_tr_sq - two_x_x_tr
X_X_tr_sq

array([[998, 725, 506, 341, 230, 173, 170, 221, 326, 485],
       [611, 404, 251, 152, 107, 116, 179, 296, 467, 692],
       [965, 734, 557, 434, 365, 350, 389, 482, 629, 830]])

In [21]:
dists = np.sqrt(X_X_tr_sq)
dists

array([[31.591138  , 26.92582404, 22.49444376, 18.46618531, 15.16575089,
        13.15294644, 13.03840481, 14.86606875, 18.05547009, 22.02271555],
       [24.71841419, 20.09975124, 15.84297952, 12.32882801, 10.34408043,
        10.77032961, 13.37908816, 17.20465053, 21.61018278, 26.30589288],
       [31.06444913, 27.09243437, 23.60084744, 20.83266666, 19.10497317,
        18.70828693, 19.72308292, 21.9544984 , 25.07987241, 28.80972058]])

In [24]:
"""
Structured SVM loss function, naive implementation (with loops).

Inputs have dimension D, there are C classes, and we operate on minibatches
of N examples.

Inputs:
- W: A numpy array of shape (D, C) containing weights.
- X: A numpy array of shape (N, D) containing a minibatch of data.
- y: A numpy array of shape (N,) containing training labels; y[i] = c means
  that X[i] has label c, where 0 <= c < C.
- reg: (float) regularization strength

Returns a tuple of:
- loss as single float
- gradient with respect to weights W; an array of same shape as W
"""
dW = np.zeros(W.shape) # initialize the gradient as zero
dW

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
# compute the loss and the gradient
num_classes = W.shape[1]
num_train = X.shape[0]
loss = 0.0

In [26]:
scores = X[0].dot(W)
scores

ValueError: shapes (3,) and (12,5) not aligned: 3 (dim 0) != 12 (dim 0)

In [22]:

for i in range(num_train):
    scores = X[i].dot(W)
    correct_class_score = scores[y[i]]
    for j in range(num_classes):
        if j == y[i]:
            continue
        # Li
        margin = scores[j] - correct_class_score + 1 # note delta = 1
        if margin > 0:
            loss += margin
            dW[:, y[i]] -= X[i, :]
            dW[:, j] += X[i, :]

# Right now the loss is a sum over all training examples, but we want it
# to be an average instead so we divide by num_train.
loss /= num_train
dW /= num_train

# Add regularization to the loss.
loss += reg * np.sum(W * W)
dW += reg * W


ValueError: operands could not be broadcast together with shapes (4,) (6,) 

In [23]:
np.concatenate((a[:2] + b[2:]))

ValueError: operands could not be broadcast together with shapes (2,) (4,) 